### ISSUE TITLE
초기화면 다시그려주세요

### ISSUE THREAD

**Issue by sangwookShin** [SHINMH/oss_snake_game#10]
**Is your feature request related to a problem? Please describe.**
초기화면 뱀 그림에서 깨지는게 있어요.

**Describe the solution you'd like**
다른문자로 바꾸면 될 것 같아요

**Describe alternatives you've considered**
empty

**Additional context**
empty.

**Comment by SHINMH** [comment]
넵 바꾸면 될거 같아요 벡슬래시가 한글용이라 (원)으로 표시되는거 때문에 일어나는 오류라 대체하는 문자로 변경하면될거 같아요
