### ISSUE TITLE
Select mode print inconnect 

### ISSUE THREAD

**Issue by SHINMH** [SHINMH/oss_snake_game#15]
**Describe the bug**
게임 모드를 선택하는 화면의 문구가 잘못되어있습니다.
현재는 'Select The game speed between 1 and 9.
수정은 'Select The game mode !!!'

**To Reproduce**
1. 게임 실행
2. 게임모드 선택

**Expected behavior**
게임 모드 문구를 위에 적인 내용처럼 수정합니다.

**Screenshots**
**Additional context**

**Comment by sangwookShin** [comment]
수정하였습니다 :)

**Comment by junpppyo** [comment]
확인했습니다
