### ISSUE TITLE
occur error when select high score in menu

### ISSUE THREAD

**Issue by SHINMH** [SHINMH/oss_snake_game#9]
**Describe the bug**
처음 화면에서 하이스코어 보기를 하면 콘솔이 팅깁니다.
아마 파일이 없는데 읽을려고 하여서 팅기는 거 같습니다. 확인 부탁드려요!!

**To Reproduce**
1. 게임을 실행함
2. 게임 메뉴에서 hign score를 선택함
3. 화면이 전환되면서 오류가 발생함

**Expected behavior**
팅기고 나서 high score로 다시 들어가면 그 때부터는 팅기지 않습니다.
아마 그 후로는 파일이 만들어져서 그런거 같습니다.

**Screenshots**

**Additional context**

**Comment by junpppyo** [comment]
수정했습니다
